apiVersion: apps/v1
kind: Deployment
metadata:
  name: edu-auth2
  namespace: dev
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: edu-auth2
  template:
    metadata:
      labels:
        app: edu-auth2
    spec:
      containers:
      - name: edu-auth2
        image: image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
        resources:
          {{- toYaml .Values.resources | nindent 12 }}